<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Learn More</name>
   <tag></tag>
   <elementGuidId>ab48ccbf-7a66-4370-b013-acdc5324ee4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.main-btn.mt-55</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='about-part']/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a19aea28-a4b5-4fbd-a324-e22474354436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.udemy.com/user/testing-minds/</value>
      <webElementGuid>33b0d6ba-d124-4cf2-ad8d-ffca1e1beef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-btn mt-55</value>
      <webElementGuid>4308d348-e43d-44bf-9f44-ef73293bae0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn More</value>
      <webElementGuid>ab0dbe54-70fe-4ef3-a42b-a243e0bb9273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;about-part&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5&quot;]/div[@class=&quot;about-cont&quot;]/a[@class=&quot;main-btn mt-55&quot;]</value>
      <webElementGuid>83140dfd-cc8e-4113-8419-3ccebbfb703e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='about-part']/div/div/div/div[2]/a</value>
      <webElementGuid>0bbe5a7d-edba-43ef-bd8b-890381774546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Learn More')]</value>
      <webElementGuid>c5cd3753-a1de-4976-9035-30de2e401b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.udemy.com/user/testing-minds/')])[3]</value>
      <webElementGuid>2612a4dc-ce51-4264-87eb-dfe5089d7fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div[2]/a</value>
      <webElementGuid>4692f29f-9622-417d-9843-c42a2b453465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.udemy.com/user/testing-minds/' and (text() = 'Learn More' or . = 'Learn More')]</value>
      <webElementGuid>a635809e-e785-4e8d-b20a-b7c12f88bb78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
