<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframecf-chl-widget-nqdeb</name>
   <tag></tag>
   <elementGuidId>cd8b295e-ec84-4db1-8db8-3a6e2ac21b64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cf-chl-widget-nqdeb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cf-chl-widget-nqdeb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a78eac90-ac8a-4d07-9916-0ad7372c5967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/g/turnstile/if/ov2/av0/rcv0/0/nqdeb/0x4AAAAAAADnPIDROrmt1Wwj/light/normal</value>
      <webElementGuid>01061be2-4d97-4dab-98ef-78f8a8d4472f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>cross-origin-isolated; fullscreen</value>
      <webElementGuid>5cfb5355-c895-49a5-8edb-51a6cfcb3469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-same-origin allow-scripts allow-popups</value>
      <webElementGuid>b4f56c85-f55a-4338-b370-7e7f00715853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cf-chl-widget-nqdeb</value>
      <webElementGuid>720ad31d-94d5-4c77-81c9-17fb0e978bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>03dbf1bd-9ca5-477f-9e13-f4dba6945607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Widget containing a Cloudflare security challenge</value>
      <webElementGuid>8e2cc63f-1676-47ac-a36d-05d591d9daf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cf-chl-widget-nqdeb&quot;)</value>
      <webElementGuid>6cacbabf-f68d-47c8-9aa6-c2bbf3719dbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cf-chl-widget-nqdeb']</value>
      <webElementGuid>88d6fe44-ea48-43c0-98b1-ce9cf148e3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='turnstile-wrapper']/div/iframe</value>
      <webElementGuid>df16b7f0-e387-44b6-84af-feb89c999941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a45673a8-0a22-4fd6-8e49-14408d22269e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/g/turnstile/if/ov2/av0/rcv0/0/nqdeb/0x4AAAAAAADnPIDROrmt1Wwj/light/normal' and @id = 'cf-chl-widget-nqdeb' and @title = 'Widget containing a Cloudflare security challenge']</value>
      <webElementGuid>428f2f6f-dc55-4c50-ab97-b5243a6950ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
