<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Appium</name>
   <tag></tag>
   <elementGuidId>3a532258-cc54-4f6d-a4b5-81e9a2b95544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gf-BIG']/table/tbody/tr/td/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18845ce8-cb73-42ce-8e4d-4f513bc6b7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.udemy.com/course/mobile-automation-using-appiumselenium-3/?referralCode=C46BF551F5B9EAF08E10</value>
      <webElementGuid>e800308c-687e-49bc-a10c-d68963756524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Appium</value>
      <webElementGuid>edf6b65a-0638-44c7-95ad-af2bc909cb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gf-BIG&quot;)/table[@class=&quot;gf-t&quot;]/tbody[1]/tr[1]/td[1]/ul[1]/li[@class=&quot;gf-li&quot;]/a[1]</value>
      <webElementGuid>34bbc9db-98e8-4545-9d3f-518d3752f1b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gf-BIG']/table/tbody/tr/td/ul/li[4]/a</value>
      <webElementGuid>11a2d14b-57c7-4896-aad9-7120ba7f6e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Appium')]</value>
      <webElementGuid>509f55a8-ac6a-466b-9aed-630b85db718e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.udemy.com/course/mobile-automation-using-appiumselenium-3/?referralCode=C46BF551F5B9EAF08E10')]</value>
      <webElementGuid>a648d4b6-eb66-40a2-aa2e-10b77e076517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>2070d41c-8846-48b7-8457-64bf1afc4496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.udemy.com/course/mobile-automation-using-appiumselenium-3/?referralCode=C46BF551F5B9EAF08E10' and (text() = 'Appium' or . = 'Appium')]</value>
      <webElementGuid>39c3f4a4-9d17-446e-acf9-4c0e987207fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
