<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JOIN NOW</name>
   <tag></tag>
   <elementGuidId>1d566c31-e153-4898-b91c-163a7c047473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-group.text-center > a.theme-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'JOIN NOW')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14edae6d-0baa-4b60-90a1-2eb3ef3b5a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-btn</value>
      <webElementGuid>cd54ab08-3350-4acc-a5f7-5b93de6478f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://courses.rahulshettyacademy.com/sign_up</value>
      <webElementGuid>3771a025-ff25-4bbd-97ba-abe50fbc7ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JOIN NOW</value>
      <webElementGuid>1487eff0-b24a-45ad-86d1-13dd65955e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-wrapper&quot;]/section[@class=&quot;subscribe-style-one&quot;]/div[@class=&quot;auto-container&quot;]/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-md-4 col-sm-12 col-xs-12&quot;]/div[@class=&quot;form-group text-center&quot;]/a[@class=&quot;theme-btn&quot;]</value>
      <webElementGuid>a82e6556-5a7b-4fca-ad7b-05332405621a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Practice Page/iframe_iframe-name</value>
      <webElementGuid>d8d17a19-c7f0-49d7-ba08-370eb24b33d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'JOIN NOW')])[2]</value>
      <webElementGuid>e8c1271d-f1c9-4321-a5e6-9d6763882c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://courses.rahulshettyacademy.com/sign_up')])[3]</value>
      <webElementGuid>2c5ce110-17f7-4709-8116-d63cbc0e8bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div/a</value>
      <webElementGuid>1a2a527d-4439-4764-97b6-8566d472a7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://courses.rahulshettyacademy.com/sign_up' and (text() = 'JOIN NOW' or . = 'JOIN NOW')]</value>
      <webElementGuid>09966460-2067-4d00-bb7c-152a7a624cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carousel-example-generic']/div/div/div/div/div/a</value>
      <webElementGuid>30b2070b-49fc-4d43-9598-0d9f645c7008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JOIN NOW')]</value>
      <webElementGuid>8513dd85-d79b-45a4-acee-67d923e9cbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://courses.rahulshettyacademy.com/sign_up')])[2]</value>
      <webElementGuid>a08fb1f0-00f9-41f4-b8f2-d1066f11045e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/a</value>
      <webElementGuid>72119814-a0b2-4c3b-adc4-74c4549584da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
