<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Open Tab</name>
   <tag></tag>
   <elementGuidId>b8821d24-9b35-4392-966d-e266cbbaa90b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#opentab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='opentab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8a1ca16-e3b9-4eb7-a9b5-e9e9b4ac41ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opentab</value>
      <webElementGuid>5f0f0c1f-a2bc-46e9-b8a8-101d123e1cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style class1 class2</value>
      <webElementGuid>952ebc90-3dac-4a94-a388-5f2b71d4cf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.qaclickacademy.com</value>
      <webElementGuid>93d14bd7-8128-4c5b-be90-de74e1f49d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a4f6e6b4-6756-4cb2-9f2d-5495b477a237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open Tab</value>
      <webElementGuid>3ebe000f-4248-4210-9ce7-1d321debdbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opentab&quot;)</value>
      <webElementGuid>1f4f36ef-12fb-43c8-bba7-fe2eb3f9b484</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='opentab']</value>
      <webElementGuid>767eca20-9dd1-4b79-850f-49efd9e1b9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Open Tab')]</value>
      <webElementGuid>cb3ac324-f91f-4880-b4cf-f56973291f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.qaclickacademy.com')]</value>
      <webElementGuid>7cf52ebf-af34-4242-bb2a-b9c3003df885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/a</value>
      <webElementGuid>9c592067-68d8-4df2-a511-4ceb5d1e5763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'opentab' and @href = 'https://www.qaclickacademy.com' and (text() = 'Open Tab' or . = 'Open Tab')]</value>
      <webElementGuid>b760714a-91ae-44c5-9f2f-9140c1d7dcce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
