<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SoapUI</name>
   <tag></tag>
   <elementGuidId>76aa4a5f-a2d6-4c86-a316-8fc7086461d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gf-BIG']/table/tbody/tr/td/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a2434aa-5e8f-4534-a415-5e73db7f6327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.soapui.org/</value>
      <webElementGuid>707de402-ed53-4ea5-8789-8490864c99b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SoapUI</value>
      <webElementGuid>3c1e277c-bd04-403b-b770-eede3ab97f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gf-BIG&quot;)/table[@class=&quot;gf-t&quot;]/tbody[1]/tr[1]/td[1]/ul[1]/li[@class=&quot;gf-li&quot;]/a[1]</value>
      <webElementGuid>9342e916-aa4f-433d-b7a9-2dff22cca117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gf-BIG']/table/tbody/tr/td/ul/li[3]/a</value>
      <webElementGuid>6455ab7a-0b65-4fa7-a7bf-5b6c8761c1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SoapUI')]</value>
      <webElementGuid>3c9674b8-b19f-4164-ad84-24b7920e14ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.soapui.org/')]</value>
      <webElementGuid>a0e5533d-3818-4f63-a82b-c853d56d2645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>591c4947-e437-44db-aa69-aba788ffee43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.soapui.org/' and (text() = 'SoapUI' or . = 'SoapUI')]</value>
      <webElementGuid>0ba93c8f-4292-47da-b610-8c0c708da6c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
