<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Open Window</name>
   <tag></tag>
   <elementGuidId>51636572-9084-421f-9752-a6f799fdd2ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#openwindow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='openwindow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad5927da-8cda-4fdc-b438-4169b0be51ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>openwindow</value>
      <webElementGuid>f0e546fe-655b-4cf1-8b48-b4c45a028df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style class1</value>
      <webElementGuid>bceca007-6917-4167-9bee-235a2a3348a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openWindow()</value>
      <webElementGuid>8e1d9a47-44bb-4959-a759-8b1447516362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open Window</value>
      <webElementGuid>5e46febb-cc67-4382-8629-f74f71900c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;openwindow&quot;)</value>
      <webElementGuid>ff6cac84-6f2a-40c5-a559-f36007c8168a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='openwindow']</value>
      <webElementGuid>9e741bf2-69d5-4530-a789-b8bf36f087db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/button</value>
      <webElementGuid>24f0d0d8-aa25-419a-b04f-f4cd71d1e740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'openwindow' and (text() = 'Open Window' or . = 'Open Window')]</value>
      <webElementGuid>5dc9c3cf-c74c-4941-b178-b5fbb70404f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
