<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Indonesia</name>
   <tag></tag>
   <elementGuidId>e90f9fbc-0b3c-4d14-a8c8-21fad7c11193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-40</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-40']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>84899fcf-2e43-4802-8c16-e0fc0fa197ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-40</value>
      <webElementGuid>0e4294c0-5136-46cf-b634-024e7d2dc7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>16c7d5db-e430-418a-85a5-058d03be3708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>6a0faf29-beb5-44ff-b33e-63232d748d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>d3f8ad15-4ecc-41d2-bd7c-854b9f632c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-40&quot;)</value>
      <webElementGuid>cc6c6747-d098-4d5d-98dc-153e156b4647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-40']</value>
      <webElementGuid>208e1cdc-1ace-49f0-8424-4e6486d6fb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li[3]/div</value>
      <webElementGuid>7d61c538-7cb5-4eb3-b584-2ed7998e081c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div</value>
      <webElementGuid>1bede08b-bbe7-4941-8589-df141b731f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-40' and (text() = 'Indonesia' or . = 'Indonesia')]</value>
      <webElementGuid>9604f0d1-52ec-49c7-8d51-a197ac906e57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
