<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e5b07001-b976-441b-8cc2-60a6f6d12f2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Core java for Automation Testers + Interview Programs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='courses-block']/div[3]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>81e6af76-876a-48ed-86fc-7a9799f98dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/courses/core-java-for-automation-testers-interview-programs_1591014818_corejava.jpg</value>
      <webElementGuid>e1558ef0-b030-4746-ace3-4549d536ca82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Core java for Automation Testers + Interview Programs</value>
      <webElementGuid>8139717a-003b-4869-9b69-22052b65304a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;courses-block&quot;)/div[@class=&quot;courses-block col-lg-3 col-md-4 col-sm-6 col-xs-12&quot;]/div[@class=&quot;inner-box&quot;]/div[@class=&quot;image&quot;]/a[1]/img[1]</value>
      <webElementGuid>ffa7df97-1783-4a90-9115-dc702f3f3ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Practice Page/iframe_iframe-name</value>
      <webElementGuid>51cdfef6-6fc0-4daf-a6c0-2c08d4ea54fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='courses-block']/div[3]/div/div/a/img</value>
      <webElementGuid>0a3bec2b-147e-41b7-b31d-e522f1b74035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Core java for Automation Testers + Interview Programs']</value>
      <webElementGuid>c382c45b-d1dd-44c6-bf57-38f61ba87909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/img</value>
      <webElementGuid>7d51fbf2-921b-4387-9f61-ae1d41735f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/courses/core-java-for-automation-testers-interview-programs_1591014818_corejava.jpg' and @alt = 'Core java for Automation Testers + Interview Programs']</value>
      <webElementGuid>1438d761-b4f9-4582-9429-e661d0ec84c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
