<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputconfirmbtn</name>
   <tag></tag>
   <elementGuidId>e0714b91-03b3-4c0c-b7ab-3dc6b742d1b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e9812bc-1031-4d00-8a83-8b8945741642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmbtn</value>
      <webElementGuid>169c4924-a076-4722-8365-d8e6477cac1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style</value>
      <webElementGuid>df10a3dc-4f51-4192-a966-13cf0f2754bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>7efe85ec-4359-4deb-ac4c-05d32a9eee67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>displayConfirm()</value>
      <webElementGuid>d2f77b17-2510-4a9f-afa6-e37ad1c016d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0ae9ec27-cdeb-4458-817f-e8b77f9419ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmbtn&quot;)</value>
      <webElementGuid>b3307d58-6418-4fac-a265-5649e7b6bb89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmbtn']</value>
      <webElementGuid>e3224c99-2b0a-40f9-b313-57b964fadf0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>35ef45d6-f592-4810-a2ae-fa9f54a4b423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmbtn' and @type = 'submit']</value>
      <webElementGuid>cfb2829e-e72c-4a84-9a96-7e7be6bfc5fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
