<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_radioButton</name>
   <tag></tag>
   <elementGuidId>be822482-4b2b-46ef-ace8-7830f43e82b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label:nth-of-type(2) > input[name=&quot;radioButton&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='radioButton'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9763c2d-adff-4160-8144-f86f9d26d580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>radio2</value>
      <webElementGuid>08575ea5-904a-44b1-bcc4-83e6b683f9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioButton</value>
      <webElementGuid>166a8600-0ae8-477e-baf1-8c39eef903ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioButton</value>
      <webElementGuid>b4a3ca7c-106c-4599-8565-7802e22d56b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5e64bb3e-1d3d-4a63-8575-421982665aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-example&quot;)/fieldset[1]/label[2]/input[@class=&quot;radioButton&quot;]</value>
      <webElementGuid>ef65cf0b-9de7-40bd-a8ad-7b2336f2a6e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='radioButton'])[2]</value>
      <webElementGuid>b0ee9f39-27a3-4d9d-a8e0-615777b4b5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radio-btn-example']/fieldset/label[2]/input</value>
      <webElementGuid>f0b4b2bf-e149-4903-89a9-920c9a1ccd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>d8e56d97-928f-494d-93eb-7cf70d89f7d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'radioButton' and @type = 'radio']</value>
      <webElementGuid>96d9f851-3e58-4bd0-aa69-ae39e174b859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
