<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkBoxOption3</name>
   <tag></tag>
   <elementGuidId>f9717c44-5c4c-44af-887d-7742cb0c5ed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkBoxOption3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkBoxOption3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32ea27d6-3f8a-40ce-a2f4-bdfa4de7a729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBoxOption3</value>
      <webElementGuid>6494fb94-c4b2-4c4e-8a9f-eedfa07f4283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>option3</value>
      <webElementGuid>3f51dc17-3324-460c-ba95-5b16c25c565f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkBoxOption3</value>
      <webElementGuid>608218a4-11bc-45cc-9388-07c82def7bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>93835d3e-e9da-420e-8c1c-35c95ab49e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkBoxOption3&quot;)</value>
      <webElementGuid>44d83a2a-0ee2-467a-ad8f-455be7acbc39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkBoxOption3']</value>
      <webElementGuid>c9fe0abb-f3a9-4949-b09e-9aa28b7b72db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkbox-example']/fieldset/label[3]/input</value>
      <webElementGuid>58008424-7f07-4d70-af9a-66e9cbfb7d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/label[3]/input</value>
      <webElementGuid>958958dd-0859-44fc-9ab7-02a824c71579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkBoxOption3' and @name = 'checkBoxOption3' and @type = 'checkbox']</value>
      <webElementGuid>4e2842dc-63b0-4bbf-b803-812de41906de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
