<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputalertbtn</name>
   <tag></tag>
   <elementGuidId>597b814b-4f7c-4141-b686-1245629e7915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alertbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alertbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f3bbe4e-ef64-49c2-a1c9-0f990c939673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alertbtn</value>
      <webElementGuid>94583ded-01eb-42b4-bdfe-edb7ff7d6e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style</value>
      <webElementGuid>53f74f8a-4730-4a32-b5b2-02956cde4241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Alert</value>
      <webElementGuid>497612b5-7824-4a34-8d85-793799f8f049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>displayAlert()</value>
      <webElementGuid>5e83a62a-9282-4f00-9c56-f663293a3988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3604e443-281a-406d-a581-1f09287aa333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alertbtn&quot;)</value>
      <webElementGuid>c004d2d8-a839-4a0e-bcff-4433c5416982</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alertbtn']</value>
      <webElementGuid>8199fb21-f16e-4734-9172-5f73788598e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>12b5a945-a50d-450a-8c6b-e52eb9346f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'alertbtn' and @type = 'submit']</value>
      <webElementGuid>fc3163fa-aaa8-4cf1-91e9-748012931d94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
